"""
Scraper for host-model *dimensions* - the data the exporter needs to scale a
borrowed 3D model to the height of the engine being designed.

catalog.json (build_catalog.py) only has the header spec-table (thrust / Isp /
mass / Pc) scraped from RealismOverhaul's Engine_Configs/ - those are MM patches
with no geometry. The physical PART definitions live in a SEPARATE mod,
KSP-RO/ROEngines, `GameData/ROEngines/PartConfigs/*.cfg`. Each is a real
`PART {}` whose `engineType = X` is the join key back to catalog.json, and whose
stack attach-nodes give the rendered height:

    native_height_m = |node_stack_top.y - node_stack_bottom.y| * rescaleFactor

(RO is 1:1 scale; KSP multiplies node offsets by rescaleFactor at load. Spot
checks: F1 -> 5.36 m (real ~5.6), RD0120 -> 4.71 m, Raptor -> 2.19 m.)

Only ~180 of catalog.json's 315 engineType tags have a ROEngines model; the rest
patch onto BDB / SXT / stock parts whose part cfgs aren't in any KSP-RO repo, and
radial SRBs have no stack nodes. Those simply get no entry here - the GUI then
falls back to a user-entered reference height (0 = "don't scale").

Output: engine_designer/catalog/roengines_models.json - a committed snapshot
(read-only reference data, like Engine_Configs/), regenerated by pointing this at
a local ROEngines checkout. Auto-detected at, in order: upstream/ROEngines (the
project's own shallow reference clone - see UPSTREAM_REPOS.md), a sibling
../ROEngines next to ksp_config/, or $ROENGINES_DIR:

    ROENGINES_DIR=/path/to/ROEngines python3 -m engine_designer.catalog.build_roengines_models

With no checkout found it just re-validates the existing snapshot and prints a
summary.

Source: https://github.com/KSP-RO/ROEngines  (GameData/ROEngines/PartConfigs/)
ROEngines is CC BY-NC-ND 4.0; only derived numeric dimensions + identifiers are
stored here, not model assets or verbatim config text.
"""
import json
import os
import re
from pathlib import Path

OUTPUT_PATH = Path(__file__).resolve().parent / "roengines_models.json"

# node_stack_top / _bottom, tolerating: an optional leading '@', tabs or spaces
# around '=', comma-or-space separated components, an optional trailing node-size
# int, and a trailing // comment. We only need the y component (index 1).
_NODE_RE_TMPL = r"^[ \t]*@?{name}[ \t]*=[ \t]*([-\d.,eE +]+?)[ \t]*(?://.*)?$"
NODE_TOP_RE = re.compile(_NODE_RE_TMPL.format(name="node_stack_top"), re.MULTILINE)
NODE_BOTTOM_RE = re.compile(_NODE_RE_TMPL.format(name="node_stack_bottom"), re.MULTILINE)
RESCALE_RE = re.compile(r"^[ \t]*@?rescaleFactor[ \t]*=[ \t]*([\d.]+)", re.MULTILINE)
NAME_RE = re.compile(r"^[ \t]*name[ \t]*=[ \t]*(\S+)", re.MULTILINE)
ENGINE_TYPE_RE = re.compile(r"^[ \t]*@?%?engineType[ \t]*=[ \t]*(\S+)", re.MULTILINE)
MODEL_RE = re.compile(r"^[ \t]*model[ \t]*=[ \t]*(\S+)", re.MULTILINE)
DIA_RE = re.compile(r"[Dd]iameter:\s*\[?([\d.]+)\s*m")


def _first_part_block(text):
    """The opening `PART { ... }` node only - everything before the first
    `@PART[` / `+PART[` MM patch (same idea as build_catalog._first_header_block).
    ROEngines part cfgs always lead with the bare PART definition."""
    for marker in ("\n@PART[", "\n+PART[", "\n@PART ", "\n+PART "):
        idx = text.find(marker)
        if idx != -1:
            text = text[:idx]
    return text


def _y_component(raw):
    """Second component of a `node_stack_*` value (the axial offset), or None."""
    parts = [p for p in re.split(r"[,\s]+", raw.strip()) if p]
    if len(parts) < 2:
        return None
    try:
        return float(parts[1])
    except ValueError:
        return None


def parse_file(path):
    text = path.read_text(errors="replace")
    block = _first_part_block(text)

    et = ENGINE_TYPE_RE.search(block)
    if not et:
        return None  # decouplers / sep motors / non-engine parts
    engine_type = et.group(1)

    top_m = NODE_TOP_RE.search(block)
    bot_m = NODE_BOTTOM_RE.search(block)
    top_y = _y_component(top_m.group(1)) if top_m else None
    bot_y = _y_component(bot_m.group(1)) if bot_m else None
    if top_y is None or bot_y is None:
        return None  # radial SRB or non-stack part: no derivable height

    rescale_m = RESCALE_RE.search(block)
    rescale = float(rescale_m.group(1)) if rescale_m else 1.0

    native_height_m = round(abs(top_y - bot_y) * rescale, 4)
    if native_height_m < 0.05:  # degenerate / placeholder nodes
        return None

    name_m = NAME_RE.search(block)
    model_m = MODEL_RE.search(block)
    dia_m = DIA_RE.search(text)

    return {
        "engine_type": engine_type,
        "part_name": name_m.group(1) if name_m else None,
        "model": model_m.group(1) if model_m else None,
        "native_height_m": native_height_m,
        "native_max_dia_m": round(float(dia_m.group(1)), 4) if dia_m else None,
        "node_stack_top_m": round(top_y * rescale, 4),
        "node_stack_bottom_m": round(bot_y * rescale, 4),
        "rescale_factor": rescale,
        "source_file": path.name,
    }


def _dedupe(entries):
    """Several ROEngines part cfgs can share one engineType (a fixed + a
    deployable-nozzle variant, an inline copy, ...). Keep the median-height
    entry per engineType - robust to vacuum variants with long extendable
    bells - and record the other source files."""
    by_type = {}
    for e in entries:
        by_type.setdefault(e["engine_type"], []).append(e)
    out = []
    for et, group in by_type.items():
        group.sort(key=lambda e: e["native_height_m"])
        pick = group[len(group) // 2]
        if len(group) > 1:
            pick = dict(pick)
            pick["alt_source_files"] = sorted(
                g["source_file"] for g in group if g["source_file"] != pick["source_file"])
        out.append(pick)
    return out


def _find_partconfigs_dir():
    env = os.environ.get("ROENGINES_DIR")
    rel = Path("GameData/ROEngines/PartConfigs")
    candidates = []
    if env:
        candidates += [Path(env) / rel, Path(env)] if Path(env).name != "PartConfigs" \
            else [Path(env)]
    repo_root = Path(__file__).resolve().parents[2]
    candidates.append(repo_root / "upstream" / "ROEngines" / "GameData/ROEngines/PartConfigs")
    for base in (repo_root.parent, repo_root, repo_root.parent.parent):
        candidates.append(base / "ROEngines" / "GameData/ROEngines/PartConfigs")
    for c in candidates:
        if c.is_dir():
            return c
    return None


def build():
    src = _find_partconfigs_dir()
    if src is None:
        _report_existing()
        return None

    entries = []
    for path in sorted(src.glob("*.cfg")):
        try:
            entry = parse_file(path)
        except Exception as exc:  # best-effort, never fatal on one file
            entry = None
            print(f"  [skip] {path.name}: {exc}")
        if entry:
            entries.append(entry)

    entries = _dedupe(entries)
    entries.sort(key=lambda e: e["engine_type"].lower())
    commit = _git_commit(src)
    payload = {"_source": "https://github.com/KSP-RO/ROEngines",
               "_commit": commit, "_count": len(entries), "models": entries}
    OUTPUT_PATH.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"Wrote {len(entries)} model entries to {OUTPUT_PATH} (ROEngines @ {commit})")
    return entries


def _git_commit(src):
    try:
        import subprocess
        return subprocess.check_output(
            ["git", "-C", str(src), "rev-parse", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"


def _report_existing():
    if not OUTPUT_PATH.is_file():
        print("No ROEngines checkout found and no snapshot present.")
        print("Set ROENGINES_DIR=/path/to/ROEngines and re-run, or clone it next "
              "to ksp_config/.")
        return
    data = json.loads(OUTPUT_PATH.read_text())
    models = data.get("models", [])
    print(f"No ROEngines checkout found; validating existing snapshot "
          f"({OUTPUT_PATH.name}, {len(models)} entries, "
          f"ROEngines @ {data.get('_commit', '?')}).")
    assert models, "snapshot has no model entries"
    for e in models:
        assert e.get("engine_type"), e
        assert isinstance(e.get("native_height_m"), (int, float)) and e["native_height_m"] > 0, e
    heights = sorted(e["native_height_m"] for e in models)
    print(f"  native_height_m range {heights[0]:.2f} - {heights[-1]:.2f} m, "
          f"median {heights[len(heights) // 2]:.2f} m")
    print("roengines_models snapshot: OK")


if __name__ == "__main__":
    build()
